name: full-wordpress-container

services:
    database:
        image: mysql:8.0-bookworm
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            TERM: ${TERM}
        cap_add:
            - SYS_NICE
        volumes:
            - database:/var/lib/mysql

    wordpress:
        depends_on:
            - database
        build:
            context: .
            dockerfile: wordpress.dockerfile
        restart: always
        environment:
            TERM: ${TERM}
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        ports:
            - "3000:80"
        volumes:
            - ./src:/var/www/html
            - ./.htaccess:/var/www/html/.htaccess

    reverse-proxy:
        depends_on:
            - wordpress
        image: caddy:2.7.6-alpine
        profiles:
            - production
        restart: always
        cap_add:
            - NET_ADMIN
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - reverse-proxy-configuration:/config
            - reverse-proxy-data:/data

volumes:
    database:
    reverse-proxy-configuration:
    reverse-proxy-data:
