# TODO: Automate personal choice of shell and dev environment with Chezmoi (togglable with env)
name: full-wordpress-container

services:
    database:
        image: mysql:8.0-bookworm
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            TERM: ${TERM}
        volumes:
            - database:/var/lib/mysql
        networks:
            - backend

    wordpress:
        depends_on:
            - database
        image: wordpress:6.5.2-php8.3-apache
        restart: unless-stopped
        environment:
            TERM: ${TERM}
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - ../src:/var/www/html
        networks:
            - backend

    reverse-proxy:
        depends_on:
            - wordpress
        image: caddy:2.7.6-alpine
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - reverse-proxy-configuration:/config
            - reverse-proxy-data:/data
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    database:
    reverse-proxy-configuration:
    reverse-proxy-data:
